<Query Kind="Program">
  <Output>DataGrids</Output>
  <Reference>&lt;RuntimeDirectory&gt;\System.Data.Entity.dll</Reference>
  <Reference>&lt;RuntimeDirectory&gt;\System.Linq.dll</Reference>
  <Reference>&lt;RuntimeDirectory&gt;\System.Linq.Expressions.dll</Reference>
  <Reference>&lt;RuntimeDirectory&gt;\System.Linq.Parallel.dll</Reference>
  <Reference>&lt;RuntimeDirectory&gt;\System.Linq.Queryable.dll</Reference>
  <NuGetReference>EOls.UmbracoContentApi</NuGetReference>
  <Namespace>AutoMapper</Namespace>
  <Namespace>AutoMapper.Impl</Namespace>
  <Namespace>AutoMapper.Internal</Namespace>
  <Namespace>AutoMapper.Mappers</Namespace>
  <Namespace>AutoMapper.QueryableExtensions</Namespace>
  <Namespace>ClientDependency.Core</Namespace>
  <Namespace>ClientDependency.Core.CompositeFiles</Namespace>
  <Namespace>ClientDependency.Core.CompositeFiles.Providers</Namespace>
  <Namespace>ClientDependency.Core.Config</Namespace>
  <Namespace>ClientDependency.Core.Controls</Namespace>
  <Namespace>ClientDependency.Core.FileRegistration.Providers</Namespace>
  <Namespace>ClientDependency.Core.Logging</Namespace>
  <Namespace>ClientDependency.Core.Module</Namespace>
  <Namespace>ClientDependency.Core.Mvc</Namespace>
  <Namespace>CookComputing.Blogger</Namespace>
  <Namespace>CookComputing.MetaWeblog</Namespace>
  <Namespace>CookComputing.XmlRpc</Namespace>
  <Namespace>dashboardUtilities</Namespace>
  <Namespace>EOls.UmbracoContentApi</Namespace>
  <Namespace>EOls.UmbracoContentApi.Attributes</Namespace>
  <Namespace>EOls.UmbracoContentApi.Interfaces</Namespace>
  <Namespace>EOls.UmbracoContentApi.PropertyConverters</Namespace>
  <Namespace>EOls.UmbracoContentApi.Setup</Namespace>
  <Namespace>EOls.UmbracoContentApi.Util</Namespace>
  <Namespace>Examine</Namespace>
  <Namespace>Examine.Config</Namespace>
  <Namespace>Examine.LuceneEngine</Namespace>
  <Namespace>Examine.LuceneEngine.Config</Namespace>
  <Namespace>Examine.LuceneEngine.Providers</Namespace>
  <Namespace>Examine.LuceneEngine.SearchCriteria</Namespace>
  <Namespace>Examine.Providers</Namespace>
  <Namespace>Examine.SearchCriteria</Namespace>
  <Namespace>Headblender.XmlRpc</Namespace>
  <Namespace>HtmlAgilityPack</Namespace>
  <Namespace>ICSharpCode.SharpZipLib</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.BZip2</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.Checksums</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.Core</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.Encryption</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.GZip</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.LZW</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.Tar</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.Zip</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.Zip.Compression</Namespace>
  <Namespace>ICSharpCode.SharpZipLib.Zip.Compression.Streams</Namespace>
  <Namespace>ImageProcessor</Namespace>
  <Namespace>ImageProcessor.Extensions</Namespace>
  <Namespace>ImageProcessor.Imaging</Namespace>
  <Namespace>ImageProcessor.Imaging.Filters</Namespace>
  <Namespace>ImageProcessor.Processors</Namespace>
  <Namespace>ImageProcessor.Web</Namespace>
  <Namespace>ImageProcessor.Web.Config</Namespace>
  <Namespace>ImageProcessor.Web.Extensions</Namespace>
  <Namespace>ImageProcessor.Web.Helpers</Namespace>
  <Namespace>ImageProcessor.Web.HttpModules</Namespace>
  <Namespace>log4net</Namespace>
  <Namespace>log4net.Appender</Namespace>
  <Namespace>log4net.Config</Namespace>
  <Namespace>log4net.Core</Namespace>
  <Namespace>log4net.DateFormatter</Namespace>
  <Namespace>log4net.Filter</Namespace>
  <Namespace>log4net.Layout</Namespace>
  <Namespace>log4net.Layout.Pattern</Namespace>
  <Namespace>log4net.ObjectRenderer</Namespace>
  <Namespace>log4net.Plugin</Namespace>
  <Namespace>log4net.Repository</Namespace>
  <Namespace>log4net.Repository.Hierarchy</Namespace>
  <Namespace>log4net.Util</Namespace>
  <Namespace>log4net.Util.TypeConverters</Namespace>
  <Namespace>Lucene.Net</Namespace>
  <Namespace>Lucene.Net.Analysis</Namespace>
  <Namespace>Lucene.Net.Analysis.Standard</Namespace>
  <Namespace>Lucene.Net.Analysis.Tokenattributes</Namespace>
  <Namespace>Lucene.Net.Documents</Namespace>
  <Namespace>Lucene.Net.Index</Namespace>
  <Namespace>Lucene.Net.Messages</Namespace>
  <Namespace>Lucene.Net.QueryParsers</Namespace>
  <Namespace>Lucene.Net.Search</Namespace>
  <Namespace>Lucene.Net.Search.ExtendedFieldCache_old</Namespace>
  <Namespace>Lucene.Net.Search.Function</Namespace>
  <Namespace>Lucene.Net.Search.Payloads</Namespace>
  <Namespace>Lucene.Net.Search.Spans</Namespace>
  <Namespace>Lucene.Net.Store</Namespace>
  <Namespace>Lucene.Net.Util</Namespace>
  <Namespace>Lucene.Net.Util.Cache</Namespace>
  <Namespace>Microsoft.ApplicationBlocks.Data</Namespace>
  <Namespace>Microsoft.Web.Helpers</Namespace>
  <Namespace>Microsoft.Web.Infrastructure</Namespace>
  <Namespace>Microsoft.Web.Infrastructure.DynamicModuleHelper</Namespace>
  <Namespace>Microsoft.Web.Infrastructure.DynamicValidationHelper</Namespace>
  <Namespace>Microsoft.Web.Mvc</Namespace>
  <Namespace>MySql.Data.MySqlClient</Namespace>
  <Namespace>MySql.Data.MySqlClient.Authentication</Namespace>
  <Namespace>MySql.Data.MySqlClient.Properties</Namespace>
  <Namespace>MySql.Data.Types</Namespace>
  <Namespace>Newtonsoft.Json</Namespace>
  <Namespace>Newtonsoft.Json.Bson</Namespace>
  <Namespace>Newtonsoft.Json.Converters</Namespace>
  <Namespace>Newtonsoft.Json.Linq</Namespace>
  <Namespace>Newtonsoft.Json.Schema</Namespace>
  <Namespace>Newtonsoft.Json.Serialization</Namespace>
  <Namespace>presentation.umbraco.webservices</Namespace>
  <Namespace>SqlCE4Umbraco</Namespace>
  <Namespace>SQLCE4Umbraco</Namespace>
  <Namespace>StackExchange.Profiling</Namespace>
  <Namespace>StackExchange.Profiling.Data</Namespace>
  <Namespace>StackExchange.Profiling.Helpers</Namespace>
  <Namespace>StackExchange.Profiling.Helpers.Dapper</Namespace>
  <Namespace>StackExchange.Profiling.MVCHelpers</Namespace>
  <Namespace>StackExchange.Profiling.SqlFormatters</Namespace>
  <Namespace>StackExchange.Profiling.Storage</Namespace>
  <Namespace>StackExchange.Profiling.UI</Namespace>
  <Namespace>System.Data.Objects.SqlClient</Namespace>
  <Namespace>System.Data.SqlServerCe</Namespace>
  <Namespace>System.Linq.Dynamic</Namespace>
  <Namespace>System.Net.Http</Namespace>
  <Namespace>System.Net.Http.Formatting</Namespace>
  <Namespace>System.Net.Http.Handlers</Namespace>
  <Namespace>System.Net.Http.Headers</Namespace>
  <Namespace>System.Web.Helpers</Namespace>
  <Namespace>System.Web.Http</Namespace>
  <Namespace>System.Web.Http.Controllers</Namespace>
  <Namespace>System.Web.Http.Dependencies</Namespace>
  <Namespace>System.Web.Http.Description</Namespace>
  <Namespace>System.Web.Http.Dispatcher</Namespace>
  <Namespace>System.Web.Http.Filters</Namespace>
  <Namespace>System.Web.Http.Hosting</Namespace>
  <Namespace>System.Web.Http.Metadata</Namespace>
  <Namespace>System.Web.Http.Metadata.Providers</Namespace>
  <Namespace>System.Web.Http.ModelBinding</Namespace>
  <Namespace>System.Web.Http.ModelBinding.Binders</Namespace>
  <Namespace>System.Web.Http.Routing</Namespace>
  <Namespace>System.Web.Http.Services</Namespace>
  <Namespace>System.Web.Http.Tracing</Namespace>
  <Namespace>System.Web.Http.Validation</Namespace>
  <Namespace>System.Web.Http.Validation.Providers</Namespace>
  <Namespace>System.Web.Http.Validation.Validators</Namespace>
  <Namespace>System.Web.Http.ValueProviders</Namespace>
  <Namespace>System.Web.Http.ValueProviders.Providers</Namespace>
  <Namespace>System.Web.Http.WebHost</Namespace>
  <Namespace>System.Web.Mvc</Namespace>
  <Namespace>System.Web.Mvc.Ajax</Namespace>
  <Namespace>System.Web.Mvc.Async</Namespace>
  <Namespace>System.Web.Mvc.Html</Namespace>
  <Namespace>System.Web.Mvc.Razor</Namespace>
  <Namespace>System.Web.Razor</Namespace>
  <Namespace>System.Web.Razor.Editor</Namespace>
  <Namespace>System.Web.Razor.Generator</Namespace>
  <Namespace>System.Web.Razor.Parser</Namespace>
  <Namespace>System.Web.Razor.Parser.SyntaxTree</Namespace>
  <Namespace>System.Web.Razor.Text</Namespace>
  <Namespace>System.Web.Razor.Tokenizer</Namespace>
  <Namespace>System.Web.Razor.Tokenizer.Symbols</Namespace>
  <Namespace>System.Web.WebPages</Namespace>
  <Namespace>System.Web.WebPages.Deployment</Namespace>
  <Namespace>System.Web.WebPages.Html</Namespace>
  <Namespace>System.Web.WebPages.Instrumentation</Namespace>
  <Namespace>System.Web.WebPages.Razor</Namespace>
  <Namespace>System.Web.WebPages.Razor.Configuration</Namespace>
  <Namespace>System.Web.WebPages.Scope</Namespace>
  <Namespace>TidyNet</Namespace>
  <Namespace>TidyNet.Dom</Namespace>
  <Namespace>umbraco</Namespace>
  <Namespace>umbraco.BasePages</Namespace>
  <Namespace>umbraco.businesslogic</Namespace>
  <Namespace>umbraco.BusinessLogic</Namespace>
  <Namespace>umbraco.BusinessLogic.Actions</Namespace>
  <Namespace>umbraco.BusinessLogic.console</Namespace>
  <Namespace>umbraco.businesslogic.Exceptions</Namespace>
  <Namespace>umbraco.BusinessLogic.Interfaces</Namespace>
  <Namespace>umbraco.businesslogic.Utils</Namespace>
  <Namespace>umbraco.BusinessLogic.Utils</Namespace>
  <Namespace>umbraco.cms</Namespace>
  <Namespace>umbraco.cms.businesslogic</Namespace>
  <Namespace>umbraco.cms.businesslogic.cache</Namespace>
  <Namespace>umbraco.cms.businesslogic.contentitem</Namespace>
  <Namespace>umbraco.cms.businesslogic.datatype</Namespace>
  <Namespace>umbraco.cms.businesslogic.datatype.controls</Namespace>
  <Namespace>umbraco.cms.businesslogic.Files</Namespace>
  <Namespace>umbraco.cms.businesslogic.installer</Namespace>
  <Namespace>umbraco.cms.businesslogic.language</Namespace>
  <Namespace>umbraco.cms.businesslogic.macro</Namespace>
  <Namespace>umbraco.cms.businesslogic.media</Namespace>
  <Namespace>umbraco.cms.businesslogic.member</Namespace>
  <Namespace>umbraco.cms.businesslogic.packager</Namespace>
  <Namespace>umbraco.cms.businesslogic.packager.repositories</Namespace>
  <Namespace>umbraco.cms.businesslogic.packager.standardPackageActions</Namespace>
  <Namespace>umbraco.cms.businesslogic.property</Namespace>
  <Namespace>umbraco.cms.businesslogic.propertytype</Namespace>
  <Namespace>umbraco.cms.businesslogic.relation</Namespace>
  <Namespace>umbraco.cms.businesslogic.Tags</Namespace>
  <Namespace>umbraco.cms.businesslogic.task</Namespace>
  <Namespace>umbraco.cms.businesslogic.template</Namespace>
  <Namespace>umbraco.cms.businesslogic.translation</Namespace>
  <Namespace>umbraco.cms.businesslogic.utilities</Namespace>
  <Namespace>umbraco.cms.businesslogic.web</Namespace>
  <Namespace>umbraco.cms.businesslogic.workflow</Namespace>
  <Namespace>umbraco.cms.helpers</Namespace>
  <Namespace>umbraco.cms.presentation</Namespace>
  <Namespace>umbraco.cms.presentation.create.controls</Namespace>
  <Namespace>umbraco.cms.presentation.developer</Namespace>
  <Namespace>umbraco.cms.presentation.developer.RelationTypes</Namespace>
  <Namespace>umbraco.cms.presentation.developer.RelationTypes.TreeMenu</Namespace>
  <Namespace>umbraco.cms.presentation.members</Namespace>
  <Namespace>umbraco.cms.presentation.settings</Namespace>
  <Namespace>umbraco.cms.presentation.settings.modal</Namespace>
  <Namespace>umbraco.cms.presentation.settings.scripts</Namespace>
  <Namespace>umbraco.cms.presentation.settings.stylesheet</Namespace>
  <Namespace>umbraco.cms.presentation.Trees</Namespace>
  <Namespace>umbraco.cms.presentation.user</Namespace>
  <Namespace>umbraco.controls</Namespace>
  <Namespace>umbraco.controls.GenericProperties</Namespace>
  <Namespace>umbraco.controls.Images</Namespace>
  <Namespace>umbraco.controls.Tree</Namespace>
  <Namespace>Umbraco.Core</Namespace>
  <Namespace>Umbraco.Core.Auditing</Namespace>
  <Namespace>Umbraco.Core.Cache</Namespace>
  <Namespace>Umbraco.Core.Configuration</Namespace>
  <Namespace>Umbraco.Core.Configuration.BaseRest</Namespace>
  <Namespace>Umbraco.Core.Configuration.Dashboard</Namespace>
  <Namespace>Umbraco.Core.Configuration.UmbracoSettings</Namespace>
  <Namespace>Umbraco.Core.Dynamics</Namespace>
  <Namespace>Umbraco.Core.Events</Namespace>
  <Namespace>Umbraco.Core.IO</Namespace>
  <Namespace>Umbraco.Core.Logging</Namespace>
  <Namespace>Umbraco.Core.Macros</Namespace>
  <Namespace>Umbraco.Core.Media</Namespace>
  <Namespace>Umbraco.Core.Models</Namespace>
  <Namespace>Umbraco.Core.Models.Editors</Namespace>
  <Namespace>Umbraco.Core.Models.EntityBase</Namespace>
  <Namespace>Umbraco.Core.Models.Mapping</Namespace>
  <Namespace>Umbraco.Core.Models.Membership</Namespace>
  <Namespace>Umbraco.Core.Models.PublishedContent</Namespace>
  <Namespace>Umbraco.Core.Models.Validation</Namespace>
  <Namespace>Umbraco.Core.ObjectResolution</Namespace>
  <Namespace>Umbraco.Core.Persistence</Namespace>
  <Namespace>Umbraco.Core.Persistence.DatabaseAnnotations</Namespace>
  <Namespace>Umbraco.Core.Persistence.DatabaseModelDefinitions</Namespace>
  <Namespace>Umbraco.Core.Persistence.FaultHandling</Namespace>
  <Namespace>Umbraco.Core.Persistence.FaultHandling.Strategies</Namespace>
  <Namespace>Umbraco.Core.Persistence.Mappers</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Initial</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Alter</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Alter.Column</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Alter.Expressions</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Alter.Table</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Create</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Create.Column</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Create.Constraint</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Create.Expressions</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Create.ForeignKey</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Create.Index</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Create.Table</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Delete</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Delete.Column</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Delete.Constraint</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Delete.DefaultConstraint</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Delete.Expressions</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Delete.ForeignKey</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Delete.Index</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Delete.Table</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Execute</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Execute.Expressions</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Expressions</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.IfDatabase</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Insert</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Insert.Expressions</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Rename</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Rename.Column</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Rename.Expressions</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Rename.Table</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Update</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Syntax.Update.Expressions</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Upgrades.TargetVersionFourNineZero</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Upgrades.TargetVersionSeven</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Upgrades.TargetVersionSevenOneZero</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Upgrades.TargetVersionSix</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Upgrades.TargetVersionSixOneZero</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Upgrades.TargetVersionSixTwoZero</Namespace>
  <Namespace>Umbraco.Core.Persistence.Migrations.Upgrades.TargetVersionSixZeroOne</Namespace>
  <Namespace>Umbraco.Core.Persistence.Querying</Namespace>
  <Namespace>Umbraco.Core.Persistence.Repositories</Namespace>
  <Namespace>Umbraco.Core.Persistence.SqlSyntax</Namespace>
  <Namespace>Umbraco.Core.Persistence.UnitOfWork</Namespace>
  <Namespace>Umbraco.Core.Profiling</Namespace>
  <Namespace>Umbraco.Core.PropertyEditors</Namespace>
  <Namespace>Umbraco.Core.PropertyEditors.ValueConverters</Namespace>
  <Namespace>Umbraco.Core.Publishing</Namespace>
  <Namespace>Umbraco.Core.Security</Namespace>
  <Namespace>Umbraco.Core.Serialization</Namespace>
  <Namespace>Umbraco.Core.Services</Namespace>
  <Namespace>Umbraco.Core.Strings</Namespace>
  <Namespace>Umbraco.Core.Sync</Namespace>
  <Namespace>Umbraco.Core.Xml</Namespace>
  <Namespace>umbraco.DataLayer</Namespace>
  <Namespace>umbraco.DataLayer.Extensions</Namespace>
  <Namespace>umbraco.DataLayer.SqlHelpers.MySql</Namespace>
  <Namespace>umbraco.DataLayer.SqlHelpers.SqlServer</Namespace>
  <Namespace>umbraco.DataLayer.Utility</Namespace>
  <Namespace>umbraco.DataLayer.Utility.Installer</Namespace>
  <Namespace>umbraco.DataLayer.Utility.Table</Namespace>
  <Namespace>umbraco.developer</Namespace>
  <Namespace>umbraco.dialogs</Namespace>
  <Namespace>umbraco.editorControls</Namespace>
  <Namespace>umbraco.editorControls.checkboxlist</Namespace>
  <Namespace>umbraco.editorControls.colorpicker</Namespace>
  <Namespace>umbraco.editorControls.datefieldmultiple</Namespace>
  <Namespace>umbraco.editorControls.datepicker</Namespace>
  <Namespace>umbraco.editorControls.dictionaryPicker</Namespace>
  <Namespace>umbraco.editorControls.dropdownlist</Namespace>
  <Namespace>umbraco.editorControls.folderbrowser</Namespace>
  <Namespace>umbraco.editorControls.imagecropper</Namespace>
  <Namespace>umbraco.editorControls.label</Namespace>
  <Namespace>umbraco.editorControls.listbox</Namespace>
  <Namespace>umbraco.editorControls.macrocontainer</Namespace>
  <Namespace>umbraco.editorControls.mediapicker</Namespace>
  <Namespace>umbraco.editorControls.memberpicker</Namespace>
  <Namespace>umbraco.editorControls.MultiNodeTreePicker</Namespace>
  <Namespace>umbraco.editorControls.MultipleTextstring</Namespace>
  <Namespace>umbraco.editorControls.numberfield</Namespace>
  <Namespace>umbraco.editorControls.pagepicker</Namespace>
  <Namespace>umbraco.editorControls.PickerRelations</Namespace>
  <Namespace>umbraco.editorControls.radiobuttonlist</Namespace>
  <Namespace>umbraco.editorControls.relatedlinks</Namespace>
  <Namespace>umbraco.editorControls.SettingControls</Namespace>
  <Namespace>umbraco.editorControls.SettingControls.Pickers</Namespace>
  <Namespace>umbraco.editorControls.simpleEditor</Namespace>
  <Namespace>umbraco.editorControls.Slider</Namespace>
  <Namespace>umbraco.editorControls.tags</Namespace>
  <Namespace>umbraco.editorControls.textfield</Namespace>
  <Namespace>umbraco.editorControls.textfieldmultiple</Namespace>
  <Namespace>umbraco.editorControls.tinymce</Namespace>
  <Namespace>umbraco.editorControls.tinyMCE3</Namespace>
  <Namespace>umbraco.editorControls.tinyMCE3.webcontrol</Namespace>
  <Namespace>umbraco.editorControls.tinyMCE3.webcontrol.plugin</Namespace>
  <Namespace>umbraco.editorControls.ultimatepicker</Namespace>
  <Namespace>umbraco.editorControls.uploadfield</Namespace>
  <Namespace>umbraco.editorControls.userControlGrapper</Namespace>
  <Namespace>umbraco.editorControls.wysiwyg</Namespace>
  <Namespace>umbraco.editorControls.XPathCheckBoxList</Namespace>
  <Namespace>umbraco.editorControls.XPathDropDownList</Namespace>
  <Namespace>umbraco.editorControls.yesno</Namespace>
  <Namespace>umbraco.interfaces</Namespace>
  <Namespace>umbraco.interfaces.skinning</Namespace>
  <Namespace>umbraco.IO</Namespace>
  <Namespace>umbraco.js</Namespace>
  <Namespace>umbraco.layoutControls</Namespace>
  <Namespace>umbraco.MacroEngines</Namespace>
  <Namespace>umbraco.MacroEngines.Library</Namespace>
  <Namespace>umbraco.MacroEngines.RazorDataTypeModels</Namespace>
  <Namespace>umbraco.NodeFactory</Namespace>
  <Namespace>umbraco.presentation</Namespace>
  <Namespace>umbraco.presentation.actions</Namespace>
  <Namespace>umbraco.presentation.channels</Namespace>
  <Namespace>umbraco.presentation.channels.businesslogic</Namespace>
  <Namespace>umbraco.presentation.create</Namespace>
  <Namespace>umbraco.presentation.developer.packages</Namespace>
  <Namespace>umbraco.presentation.dialogs</Namespace>
  <Namespace>umbraco.presentation.masterpages</Namespace>
  <Namespace>umbraco.presentation.members</Namespace>
  <Namespace>umbraco.presentation.nodeFactory</Namespace>
  <Namespace>umbraco.presentation.plugins.tinymce3</Namespace>
  <Namespace>umbraco.presentation.preview</Namespace>
  <Namespace>umbraco.presentation.Search</Namespace>
  <Namespace>umbraco.presentation.settings</Namespace>
  <Namespace>umbraco.presentation.templateControls</Namespace>
  <Namespace>umbraco.presentation.tinymce3</Namespace>
  <Namespace>umbraco.presentation.translation</Namespace>
  <Namespace>umbraco.presentation.umbraco</Namespace>
  <Namespace>umbraco.presentation.umbraco.channels</Namespace>
  <Namespace>umbraco.presentation.umbraco.controls</Namespace>
  <Namespace>umbraco.presentation.umbraco.create</Namespace>
  <Namespace>umbraco.presentation.umbraco.developer.Xslt</Namespace>
  <Namespace>umbraco.presentation.umbraco.dialogs</Namespace>
  <Namespace>umbraco.presentation.umbraco.masterpages</Namespace>
  <Namespace>umbraco.presentation.umbraco.members</Namespace>
  <Namespace>umbraco.presentation.umbraco.plugins.tinymce3</Namespace>
  <Namespace>umbraco.presentation.umbraco.Search</Namespace>
  <Namespace>umbraco.presentation.umbraco.translation</Namespace>
  <Namespace>umbraco.presentation.umbraco.webservices</Namespace>
  <Namespace>umbraco.presentation.umbraco_client.tinymce3.plugins.spellchecker</Namespace>
  <Namespace>umbraco.presentation.urlRewriter</Namespace>
  <Namespace>umbraco.presentation.Web.UI</Namespace>
  <Namespace>umbraco.presentation.webservices</Namespace>
  <Namespace>umbraco.providers</Namespace>
  <Namespace>umbraco.providers.members</Namespace>
  <Namespace>umbraco.scripting</Namespace>
  <Namespace>umbraco.settings</Namespace>
  <Namespace>umbraco.uicontrols</Namespace>
  <Namespace>umbraco.uicontrols.DatePicker</Namespace>
  <Namespace>umbraco.uicontrols.TreePicker</Namespace>
  <Namespace>umbraco.Utils</Namespace>
  <Namespace>Umbraco.Web</Namespace>
  <Namespace>Umbraco.Web.BaseRest</Namespace>
  <Namespace>Umbraco.Web.Cache</Namespace>
  <Namespace>Umbraco.Web.Controllers</Namespace>
  <Namespace>Umbraco.Web.Dynamics</Namespace>
  <Namespace>Umbraco.Web.Editors</Namespace>
  <Namespace>Umbraco.Web.Install.Controllers</Namespace>
  <Namespace>Umbraco.Web.Install.Models</Namespace>
  <Namespace>Umbraco.Web.Macros</Namespace>
  <Namespace>Umbraco.Web.Media</Namespace>
  <Namespace>Umbraco.Web.Media.EmbedProviders</Namespace>
  <Namespace>Umbraco.Web.Media.EmbedProviders.Settings</Namespace>
  <Namespace>Umbraco.Web.Media.ImageUrlProviders</Namespace>
  <Namespace>Umbraco.Web.Media.ThumbnailProviders</Namespace>
  <Namespace>Umbraco.Web.Models</Namespace>
  <Namespace>Umbraco.Web.Models.ContentEditing</Namespace>
  <Namespace>Umbraco.Web.Models.Trees</Namespace>
  <Namespace>Umbraco.Web.Mvc</Namespace>
  <Namespace>Umbraco.Web.org.umbraco.our</Namespace>
  <Namespace>Umbraco.Web.org.umbraco.update</Namespace>
  <Namespace>Umbraco.Web.PropertyEditors</Namespace>
  <Namespace>Umbraco.Web.PropertyEditors.ParameterEditors</Namespace>
  <Namespace>Umbraco.Web.PropertyEditors.ValueConverters</Namespace>
  <Namespace>Umbraco.Web.PublishedCache</Namespace>
  <Namespace>Umbraco.Web.Routing</Namespace>
  <Namespace>Umbraco.Web.Search</Namespace>
  <Namespace>Umbraco.Web.Security</Namespace>
  <Namespace>Umbraco.Web.Security.Providers</Namespace>
  <Namespace>Umbraco.Web.Strategies</Namespace>
  <Namespace>Umbraco.Web.Strategies.DataTypes</Namespace>
  <Namespace>Umbraco.Web.Strategies.Migrations</Namespace>
  <Namespace>Umbraco.Web.Strategies.Publishing</Namespace>
  <Namespace>Umbraco.Web.Templates</Namespace>
  <Namespace>Umbraco.Web.Trees</Namespace>
  <Namespace>Umbraco.Web.UI</Namespace>
  <Namespace>Umbraco.Web.UI.Bundles</Namespace>
  <Namespace>Umbraco.Web.UI.Config.Splashes</Namespace>
  <Namespace>Umbraco.Web.UI.Controls</Namespace>
  <Namespace>Umbraco.Web.UI.Install.Steps.Skinning</Namespace>
  <Namespace>Umbraco.Web.UI.JavaScript</Namespace>
  <Namespace>Umbraco.Web.UI.Pages</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Controls</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Controls.Images</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Create</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Dashboard</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Developer.Macros</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Developer.Packages</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Developer.Python</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Dialogs</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Masterpages</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Search</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Settings</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Settings.Stylesheet</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Settings.Stylesheet.Property</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Settings.Views</Namespace>
  <Namespace>Umbraco.Web.UI.Umbraco.Users</Namespace>
  <Namespace>Umbraco.Web.WebApi</Namespace>
  <Namespace>Umbraco.Web.WebApi.Filters</Namespace>
  <Namespace>Umbraco.Web.WebServices</Namespace>
  <Namespace>umbraco.webservices</Namespace>
  <Namespace>UmbracoExamine</Namespace>
  <Namespace>UmbracoExamine.Config</Namespace>
  <Namespace>UmbracoExamine.DataServices</Namespace>
  <Namespace>UmbracoExamine.LocalStorage</Namespace>
  <Namespace>UrlRewritingNet.Configuration</Namespace>
  <Namespace>UrlRewritingNet.Configuration.Provider</Namespace>
  <Namespace>UrlRewritingNet.Web</Namespace>
  <Namespace>xmlrpc</Namespace>
</Query>

void Main()
{
	var connection = new DbConnection("***", "***");
	connection.Query<IEnumerable<object>>("SELECT name, filename FROM sys.sysdatabases");
}

public class VillaBookController : Umbraco.Web.WebApi.UmbracoApiController
{
		
}

// Define other methods and classes here
public class DbConnection 
{
	private const string ConnectionStringFormat = "Server=tcp:cmgx.database.windows.net,1433;Initial Catalog=Umbraco-Playground;Persist Security Info=False;User ID={0};Password={1};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
	
	private string _userName;
	private string _password;
	
	public DbConnection(string userName, string password)
	{
		_userName = userName;
		_password = password;
	}
	
	public T Query<T>(string queryText)
	{
		using (SqlConnection connection =
			  new SqlConnection(string.Format(ConnectionStringFormat, _userName, _password)))
		{
			var command = new SqlCommand(queryText, connection);
			try
			{
				connection.Open();
				var reader = command.ExecuteReader();
				while (reader.Read())
				{
					Console.WriteLine("\t{0}\t{1}\t{2}",
						reader[0], reader[1], reader[2]);
				}
				reader.Close();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.Message);
			}
			Console.ReadLine();
		}
		
		return default (T);
	}
}